### ISSUE TITLE
insufficient qty available for order

### ISSUE THREAD

**Issue by AxelGard** [alpacahq/alpaca-trade-api-python#129]
is there a way of checking the availability of stock so that I don't get 
`alpaca_trade_api.rest.APIError: insufficient qty available for order (requested: X, available: Y)`
what do I need to do to get **Y** instead?
In other words, how do I get how many available stocks there are for a specific stock?

**Comment by ttt733** [comment]
This error is referring to the number of shares available in your account, not in the market itself. It's important to note that, if you have a long position, you can't sell more shares than you have. You need to close your open position before you can submit and order that would open a short position. (The same is true for going from a short position to a long one.)

**Comment by qwertzguy** [comment]
Is there any update on supporting this? Many algo trading frameworks assume it is possible to go from long to short directly by submitting an order that is larger than the current quantity owned. Having to separate it also impact the speed of execution since then the program needs to wait for the first order to fill before being able to enter short.

**Comment by shlomikushchi** [comment]
Hi @qwertzguy , 
it still works the same way. 
you should open this feature request at the right location: https://forum.alpaca.markets/c/alpaca/feature-requests/14

**Comment by Tomw3115** [comment]
Also,  I'm trying to place orders during market closed hours to execute on market open, but it won't take the order that switches direction (i.e.,short to long)
