### ISSUE TITLE
Assets missing from Alpaca, but are available on Polygon?

### ISSUE THREAD

**Issue by cnaccio** [alpacahq/alpaca-trade-api-python#359]
Hey Guys,

I just realized the Alpaca assets endpoint is missing some tickers that Polygon has available. Am I missing something, or using the API incorrectly?

Few Examples:

- SPEX
- TOCA
- PIH
- DCIX
- SBOT

**Comment by shlomikushchi** [comment]
Hi, from the Alpaca docs: `Some assets are only available for data consumption via Polygon, and are not tradable with Alpaca`

**Comment by cnaccio** [comment]
Hey @shlomikushchi thanks for that. While that does seem to be the issue on some of these names, I actually discovered the issue with most of them is that the tickers have changed. I was able to pull up the figi ID's for these symbols at the time they were active, and was able to utilize that to find the current tickers which were available via the Alpaca API. 

Example: TOCA's cfigi is BBG001J2N4H0 whose current symbol is FBRX which is available via the Alpaca API. Hope this helps others!

**Comment by faisalanjum** [comment]
Hi @cnaccio - Although this is a bit unrelated, but I am scratching my head trying to reconcile Alpaca assets to their respective "FIGI" identifiers as  apparently you require a ticker as well as an exchange mic in order to retrieve FIGI from openfigi API. Now the issue is Alpaca only provides exchange name/code and I can't tie it to any specific exchange "mic".
Any pointers will be much appreciated.
