### ISSUE TITLE
Possible to add attribute to Position object?

### ISSUE THREAD

**Issue by jblewdv** [alpacahq/alpaca-trade-api-python#52]
For my given algorithm I need to keep track of how many days each position has been held. So far, I haven't been able to find any built-in functionality for this. Correct me if I'm wrong please.

Is it possible to add an attribute called "Duration" to each position object and increment the time held myself?

**Comment by ttt733** [comment]
The feature request I just opened in our Alpaca-API issue tracker will be needed for this.

**Comment by bdowling** [comment]
You could today, correlate your latest orders with your positions to find when the position was opened.  Because positions can be a rollup of multiple orders or legs in/out of the position, the time-held does not have a singular meaning in the positions API.

@jblewdv I'm going to close this issue for now, as we'll track the upstream issue in the API.
